title: "Remote theme example"
remote_theme: pmarsceill/just-the-docs
color_scheme: "dark"
search_enabled: false

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vedangasdarkninja.github.io"
